version: '3'
services:
  # nodejs-server:
  #   build:
  #     context: ./api
  #   ports:
  #     - "3080:3080"
  #   container_name: node-api
  #   volumes:
  #      - ./api:/usr/src/app/api
  #      - /usr/src/app/api/node_modules
  mysql:
    image: 'mysql:5.7'
    working_dir: /app
    volumes:
        - './backend:/app'
    environment:
        - MYSQL_ROOT_PASSWORD=livre
        - MYSQL_DATABASE=academic
        - MYSQL_PASSWORD=livre
    ports:
        - '5002:3306'
  webserver:
    image: 'nginx:alpine'
    working_dir: /app
    volumes:
        - './backend:/app'
        - './backend/phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
    ports:
        - '5000:80'
  php-fpm:
    build: ./backend/phpdocker/php-fpm
    working_dir: /app
    volumes:
      - './backend:/app'
      - './backend/phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini'
  react-ui:
    build:
      context: ./my-app
    ports:
      - "3000:3000"
    container_name: react-ui
    stdin_open: true
    volumes:
       - ./my-app:/usr/src/app/my-app
       - /usr/src/app/my-app/node_modules